# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
    - job: FirstJob
      steps:
      - bash: echo 'First Job'
    - job: SecondJob
      steps:
      - bash: echo 'First Job'
  - stage: DevDeploy
    dependsOn: Build  
    variables:
      environment: DEV  
    jobs:
    - job: FirstJob
      steps:
      - bash: echo 'First Job.. ${environment}'
      - bash: echo 'Build no.. ${Build.BuildNumber}'
      - bash: echo 'Build Id.. ${Build.BuildId}'
      - bash: echo 'Build Src Branch name.. ${Build.SourceBranchName}'
      - bash: echo 'Build Stg Dir.. ${Build.ArtifactStagingDirectory}'
      - bash: java -version
      - bash: go --version
      - bash: node --version
    - job: SecondJob
      steps:
      - bash: echo 'First Job'
  - stage: QADeploy
    variables:
      environment: QA
    dependsOn: Build
    jobs:
    - job: FirstJob
      steps:
      - bash: echo 'First Job'
    - job: SecondJob
      steps:
      - bash: echo 'First Job'
  - stage: ProdDeploy
    variables:
      environment: PROD
    dependsOn:
      - QADeploy
      - DevDeploy
    jobs:
    - job: FirstJob
      steps:
      - bash: echo 'First Job'
    - job: SecondJob
      steps:
      - bash: echo 'First Job'
  
  