# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildStage
    jobs:
    - job: Build
      steps:
      - bash: echo 'Building...'
    - job: Deploy
      steps:
        - bash: echo 'Pre deploy'
    - deployment: DevDeploy
      environment: Dev
      strategy:
        runOnce:
          deploy:
            steps:
              - bash: echo 'Deploying to Dev'
